### ISSUE TITLE
CPolygon enclosing not correctly detected

### ISSUE THREAD

**Issue by icosac** [skramm/homog2d#10]
Hello,

First of, let me tell you that you have done really an impressive work. 

I've just started using your library to check two things: 1. intersection between different polygons and between polygons and circles, and 2. enclosing of circles/polygons in polygons. 

It worked flawlessly for almost everything, but I'm now facing a problem that I can't understand if it's a bug or if it's intended to be as this. 

By reading the documentation, [this part](https://github.com/skramm/homog2d/blob/master/docs/homog2d_manual.md#52---enclosing-determination) in particular, I was under the impression that it is possible to determine whether a polygon is enclosed within another. 

But by running this code:

```c++
int main (){
  h2d::CPolyline rect(std::vector<h2d::Point2d>{
      h2d::Point2d(-2, 2),
      h2d::Point2d(-2,-2),
      h2d::Point2d( 2,-2),
      h2d::Point2d( 2, 2),
  });
  std::cout << "rect closed: " << rect.isClosed() << std::endl;

  h2d::CPolyline map(std::vector<h2d::Point2d>{
      h2d::Point2d(-5, 5),
      h2d::Point2d(-5,-5),
      h2d::Point2d( 5,-5),
      h2d::Point2d( 5, 5)
  });
  std::cout << "map closed: " << map.isClosed() << std::endl;

  std::cout << "map: " << map << std::endl;
  std::cout << "rect: " << rect << std::endl;

  std::cout << "rect intersects map: " << rect.intersects(map).size() << std::endl;
  std::cout << "rect is inside map: " << rect.isInside(map) << std::endl;
  for (auto p : rect.getPts()){
    std::cout << "point " << p << " is inside map: " << p.isInside(map) << std::endl;
  }

  return 0;
}
```

The output I get is the following:

```text
rect closed: 1
map closed: 1
map: CPolyline: [-5,5]-[-5,-5]-[5,-5]-[5,5]-
rect: CPolyline: [-2,2]-[-2,-2]-[2,-2]-[2,2]-
rect intersects map: 0
rect is inside map: 0
point [-2,2] is inside map: 1
point [-2,-2] is inside map: 1
point [2,-2] is inside map: 1
point [2,2] is inside map: 1
```

Now the strange thing is that by using (CLion) debugger on the `rect.isInside(map)` instruction, it brings me to 

```c++
/// This function is a fallback for all sub-classes that do not provide such a method.
/**
It is necessary in a run-time polymorphism context, as we would have build failures if a given type disallows providing such a method
(for example, when trying to check if some object is inside an open polyline).
*/
template<typename T>
constexpr bool isInside( const Common<T>& ) const
{
  return false;
}
```

Which would be find if I weren't using CPolygon but OPolygon. 

I'm not sure if it's a problem of how I set my data or if there is a missing instruction in the library for the CPolygon.

**Comment by skramm** [comment]
Bug confirmed, it seems that some SFINAE does not trigger correctly. Besides, noticed this wasn't tested!
Fix in progress...

**Comment by skramm** [comment]
Fixed (AFAIK)
I had an error in a traits class (reversed types), and the algorithm had an error too: a closed Polyline is inside another only if there are no intersection. That was fixed, and I added 20 more unit tests.
Could you please either pull, or fetch the current "homog2d.hpp" file, and see if everything is ok for you, so I can close this issue?

**Comment by icosac** [comment]
I can confirm you that it's now working fine for me. 
Thank you for your swift response and help
