### ISSUE TITLE
compilation error on msvc 19.28

### ISSUE THREAD

**Issue by toge** [skramm/homog2d#2]
There is another compilation error on msvc 19.28.

```
https://raw.githubusercontent.com/skramm/homog2d/master/homog2d.hpp(2954): error C2063: 'h2d::operator *': not a function
```
Please refer godbolt: https://godbolt.org/z/61brssf9x 

It works fine with gcc, clang and apple-clang.
Is there any way to fix this?

**Comment by skramm** [comment]
Thanks for reporting this, I'll check this ASAP!

**Comment by toge** [comment]
@skramm 
Thanks a lot!

**Comment by skramm** [comment]
Investigating. Could be a MS bug, golbolt uses v19.28 and there seems to be an issue:
https://stackoverflow.com/questions/63288453/visual-studio-2019-c-not-recognizing-template-friends

I'll try to find a workaround.

**Comment by skramm** [comment]
I created a branch to handle that.
I think I got it fixed: added a forward declaration to the faulty friend declaration. I tried for some msvc releases (19.30, 19.28) seems fixed.
@toge , could you try and confirm that it is ok now?
https://godbolt.org/z/89nhG76rY
If ok, I'll merge into master.

**Comment by skramm** [comment]
Tested locally with msvc19.34 (with the help of Docker container provided by https://github.com/mstorsjo/msvc-wine ), seems ok.

**Comment by toge** [comment]
What a great work!
I confirmed it works fine on my environment.

**Comment by skramm** [comment]
Merged with master, closing.
