### ISSUE TITLE
Feature to consider: Disable console messages (std::cerr) at will. 

### ISSUE THREAD

**Issue by DJuego** [skramm/homog2d#8]
I understand that homog2d is not originally intended to address the requirements of speed-critical applications (such as real-time camera streams). However, some easy optimization in that sense could be considered. For instance, It would be nice if there was some way to disable the messages that are emitted right now by std::cerr. 

For example; at the moment, although the result I get is perfect for my purposes, the console just spits out the execution of this line thousands of times.

```cpp
std::cerr << "homog2d: angle computation overflow detected, value "
			<< std::scientific << std::setprecision(20)
			<< fres << ", truncated to 1.0\n";
```
"1.0000000000000000000224 or so (I can't quite remember), is truncated to 1.0." Ah. Well, that's great. :-)

I don't doubt that it is interesting to know that this event is occurring, but I can't do anything about it at this time. 

I also honestly don't think this is a performance bottleneck for my application. Probably not. :-D But another added benefit is that noise in console would be reduced. 

I suggest more control over this kind of messages (perhaps conditional compilation).

DJuego

**Comment by skramm** [comment]
Yep, that was something I did consider, but didn't think it would fit in the "important" category.
But, yes, thanks for pointing this out, I'll figure some way to disable/enable those warnings (only one at present, but could expand).
Yes, could be thought some build symbol, like `HOMOG2D_NOCHECKS`. But needs to be different, because users may want to keep runtime checkings but without bothering about such warnings.

I leave this issue open until fixed (should be fast).

**Comment by DJuego** [comment]
Yes, yes, of course it doesn't fall into the "important" category. It is a rather minor detail. Don't worry. And in fact even I myself am able to get around the problem with my limited knowledge. :grinning:

There are other things, such as the concept of the "Unit Vector", that I have missed much more. Lines and segments lack "directionality", and so I had to find a way to obtain angles between "vectors" (-PI,+PI).

But I suspect that the decision not to work with vectors was deliberate on your part, and has to do with the homog2d philosophy. :tokyo_tower:

DJuego

**Comment by DJuego** [comment]
Sorry for the delay!

 I tested it yesterday and can confirm that it seems to work great. :-D You can close this thread with the feature request fulfilled.

Again. **thank you**! :kissing_heart:

DJuego

**Comment by skramm** [comment]
Great!
About the directionality issue you mentioned, I have thought about some ideas, but I'm not sure I understand your needs. Don't hesitate to open an issue describing exactly the feature you think is missing, and how it could be used, from a user point of view.
